version: '3.8'

services:
  postgres:
    image: postgres
    container_name: prova-b2-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prova
      POSTGRES_DB: prova-b2
    volumes:
      - ./data/pg:/data/postgres
